### ISSUE TITLE
Black pawns capture forward

### ISSUE THREAD

**Issue by MarkusH** [tux21b/ChessBuddy#1]
Have a look at these steps:
1. a2-a4 h7-h5
2. d2-d4 d7-d5
3. e2-e3 c7-c6
4. f2-f4 f7-f5
5. b2-b4 b7-b5
6. a4xb5 a7-a6
7. b5xa6 Nb8xa6
8. h2-h4 Na6-b8
9. Bf1-b5 c6-c5
10. c2-c3 d5xd4
11. c3xd4 c5-c4
12. f4xf5 h5xh4

As you can see, the pawns (black an white) can capture other figures that are straight ahead (step 12). But as far as I know, they are only allowed to capture on a diagonal position. The white player is able to capture diagonal as well (11.1), but the black one is not able.

**Comment by tux21b** [comment]
Oh, you are right. There are sill some rough edges throughout the game, but I think the pawn movement works now after the last commit. Many thanks for the detailed report!

https://github.com/tux21b/ChessBuddy/commit/0338e7ec59f188b36b3ddd90d181b7693461635f
