### ISSUE TITLE
Project Structure?

### ISSUE THREAD

**Issue by Crisfole** [tux21b/ChessBuddy#3]
Hey, I'm interested in Go, and trying to figure out standard project structure. I noticed that your main.go code includes itself via its github address (see https://github.com/tux21b/ChessBuddy/blob/master/main.go#L13).  Is that standard?

This could just be a question or it could be an actual issue.

**Comment by tux21b** [comment]
Yes, that's quite common. Import paths in Go are arbitrary strings, but the "go get" command is able to interpret them as URLs. So, if you type "go get github.com/tux21b/ChessBuddy" the go tool would automatically do a git checkout in "$GOPATH/src/github.com/tux21b/ChessBuddy". In addition to that, the go tool will also do a hg checkout of "code.google.com/p/go.net/websocket" and any other packages that are used in my project. After that, the "go get" command automatically builds all those packages and commands and installs them to "$GOPATH/bin" by default.

**Comment by Crisfole** [comment]
Great, thanks for the information!
